<svelte:head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title>Privacy Policy</title>
</svelte:head>
<div class="md:px-20 mx-auto max-w-4xl mt-10">
	<strong>Privacy Policy</strong>
	<p>
		Code Carton, LLC built the Ditches app as a Commercial app. This SERVICE is provided by Code
		Carton, LLC and is intended for use as is.
	</p>
	<p>
		This page is used to inform visitors regarding our policies with the collection, use, and
		disclosure of Personal Information if anyone decided to use our Service.
	</p>
	<p>
		If you choose to use our Service, then you agree to the collection and use of information in
		relation to this policy. The Personal Information that we collect is used for providing and
		improving the Service. We will not use or share your information with anyone except as described
		in this Privacy Policy.
	</p>
	<p>
		The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions,
		which are accessible at Ditches unless otherwise defined in this Privacy Policy.
	</p>
	<p><strong>Information Collection and Use</strong></p>
	<p>We do not collect any information that could be identified as yours.</p>
	<!---->
	<p><strong>Log Data</strong></p>
	<p>
		We want to inform you that whenever you use our Service, in a case of an error in the app we
		collect data and information on your phone called Log Data. This Log Data may include
		information such as device version, operating system version, the configuration of the app when
		utilizing our Service, the time and date of your use of the Service, and other statistics.
	</p>
	<p><strong>Cookies</strong></p>
	<p>Ditches does not use any cookies.</p>

	<p><strong>Security</strong></p>
	<p>We value your trust, thus we do not collect any personal information about you.</p>
	<p><strong>Links to Other Sites</strong></p>
	<p>
		This Service may contain links to other sites. If you click on a third-party link, you will be
		directed to that site. Note that these external sites are not operated by us. Therefore, we
		strongly advise you to review the Privacy Policy of these websites. We have no control over and
		assume no responsibility for the content, privacy policies, or practices of any third-party
		sites or services.
	</p>
	<p><strong>Children's Privacy</strong></p>
	<!---->
	<div>
		<p>
			We do not knowingly collect personally identifiable information from children. We encourage
			all children to never submit any personally identifiable information through the Application
			and/or Services. We encourage parents and legal guardians to monitor their children's Internet
			usage and to help enforce this Policy by instructing their children never to provide
			personally identifiable information through the Application and/or Services without their
			permission. If you have reason to believe that a child has provided personally identifiable
			information to us through the Application and/or Services, please contact us. You must also be
			at least 16 years of age to consent to the processing of your personally identifiable
			information in your country (in some countries we may allow your parent or guardian to do so
			on your behalf).
		</p>
	</div>
	<p><strong>Changes to This Privacy Policy</strong></p>
	<p>
		We may update our Privacy Policy from time to time. Thus, you are advised to review this page
		periodically for any changes. We will notify you of any changes by posting the new Privacy
		Policy on this page.
	</p>
	<p>This policy is effective as of 2024-05-07</p>
	<p><strong>Contact Us</strong></p>
	<p>
		If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us
		at hello@codecarton.com.
	</p>
	<p style="margin-top: 200px;">
		This privacy policy page was created at <a
			href="https://privacypolicytemplate.net"
			target="_blank"
			rel="noopener noreferrer"
			>privacypolicytemplate.net
		</a>and modified/generated by
		<a
			href="https://app-privacy-policy-generator.nisrulz.com/"
			target="_blank"
			rel="noopener noreferrer">App Privacy Policy Generator</a
		>
	</p>
</div>

<style>
	strong {
		display: block;
		margin-top: 20px;
	}
</style>
